"""initial schema

Revision ID: 0001
Revises: None
Create Date: 2026-07-26 00:00:00.000000

Hand-written (not autogenerated) because of Supabase/pgvector specifics:
  - CREATE EXTENSION vector          (pgvector)
  - HNSW index on document_chunks.embedding
  - GIN index on document_chunks.search_vector
  - Trigger to auto-populate search_vector from content
  - RLS enabled on all tables (policies added separately)
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 0. Extensions
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ------------------------------------------------------------------
    # 1. users  (mirrors auth.users — one row per Supabase auth user)
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")

    # ------------------------------------------------------------------
    # 2. source_documents  (one row per SEC filing)
    # ------------------------------------------------------------------
    op.create_table(
        "source_documents",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("ticker", sa.String(10), nullable=False),
        sa.Column("company_name", sa.String(255), nullable=False),
        sa.Column("filing_type", sa.String(20), nullable=False),
        sa.Column("filing_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("year", sa.Integer, nullable=False),
        sa.Column("accession_number", sa.String(50), nullable=False, unique=True),
        sa.Column("source_url", sa.Text, nullable=False),
        sa.Column("content_md", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.execute("ALTER TABLE source_documents ENABLE ROW LEVEL SECURITY;")

    # ------------------------------------------------------------------
    # 3. document_chunks  (retrieval-ready passages with embeddings)
    # ------------------------------------------------------------------
    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("source_documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        # vector(768) — Gemini text-embedding-004
        sa.Column("embedding", Vector(768), nullable=True),
        # populated by trigger below; GIN-indexed for full-text search
        sa.Column("search_vector", TSVECTOR, nullable=True),
        sa.Column("token_count", sa.Integer, nullable=True),
        sa.Column("chunk_metadata", JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    # Standard B-tree index on foreign key
    op.create_index(
        "ix_document_chunks_document_id",
        "document_chunks",
        ["document_id"],
    )
    # HNSW index for approximate nearest-neighbour search (cosine similarity)
    # m=16 / ef_construction=64 are safe defaults for 768-dim embeddings.
    op.execute(
        """
        CREATE INDEX ix_document_chunks_embedding_hnsw
        ON document_chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
        """
    )
    # GIN index for full-text search on the tsvector column
    op.execute(
        """
        CREATE INDEX ix_document_chunks_search_vector_gin
        ON document_chunks
        USING gin (search_vector);
        """
    )
    # Trigger: auto-update search_vector whenever content is inserted/updated
    op.execute(
        """
        CREATE OR REPLACE FUNCTION trg_fn_document_chunks_search_vector()
        RETURNS trigger
        LANGUAGE plpgsql AS
        $$
        BEGIN
            NEW.search_vector := to_tsvector('english', NEW.content);
            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_document_chunks_search_vector
        BEFORE INSERT OR UPDATE OF content
        ON document_chunks
        FOR EACH ROW
        EXECUTE FUNCTION trg_fn_document_chunks_search_vector();
        """
    )
    op.execute("ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;")

    # ------------------------------------------------------------------
    # 4. chat_threads  (a conversation session owned by one user)
    # ------------------------------------------------------------------
    op.create_table(
        "chat_threads",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(255),
            nullable=False,
            server_default=sa.text("'New conversation'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_chat_threads_user_id", "chat_threads", ["user_id"])
    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY;")

    # ------------------------------------------------------------------
    # 5. chat_messages  (a single user or assistant message in a thread)
    # ------------------------------------------------------------------
    op.create_table(
        "chat_messages",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "thread_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("chat_threads.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.String(20), nullable=False),  # "user" | "assistant"
        sa.Column("content", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_chat_messages_thread_id", "chat_messages", ["thread_id"])
    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;")

    # ------------------------------------------------------------------
    # 6. message_citations  (links an assistant message to a chunk)
    # ------------------------------------------------------------------
    op.create_table(
        "message_citations",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "message_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("chat_messages.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "chunk_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("document_chunks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("citation_index", sa.Integer, nullable=False),
        sa.Column("excerpt", sa.Text, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_message_citations_message_id", "message_citations", ["message_id"])
    op.execute("ALTER TABLE message_citations ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # Drop in reverse dependency order
    op.execute("DROP TABLE IF EXISTS message_citations CASCADE;")
    op.execute("DROP TABLE IF EXISTS chat_messages CASCADE;")
    op.execute("DROP TABLE IF EXISTS chat_threads CASCADE;")
    op.execute("DROP TRIGGER IF EXISTS trg_document_chunks_search_vector ON document_chunks;")
    op.execute("DROP FUNCTION IF EXISTS trg_fn_document_chunks_search_vector;")
    op.execute("DROP TABLE IF EXISTS document_chunks CASCADE;")
    op.execute("DROP TABLE IF EXISTS source_documents CASCADE;")
    op.execute("DROP TABLE IF EXISTS users CASCADE;")
    # NOTE: extension is intentionally NOT dropped — other Supabase internals
    # may depend on pgvector.  Drop manually only if you know it's safe.
